config/routes.rb
SfsLanguages::Application.routes.draw do

  devise_for :users

  resources :language_tables

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :words_subthemes

  resources :words

  get "subtheme/show"

  resources :subthemes

  get "theme/show"

  resources :themes

  get "welcome/index"

  get "languages/show"

  match ':language_id/:theme_id/:subtheme_id/:word_id' => 'words#show'

  resources :languages do
    resources :themes do
      resources :subthemes do
        resources :words
      end
    end
  end

  root :to => 'welcome#index'
  ActiveAdmin.routes(self)

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/language.rb
class Language < ActiveRecord::Base
  attr_accessible :description, :name, :name_english, :language_identifier
  has_many :themes
end

app/models/subtheme.rb
class Subtheme < ActiveRecord::Base
  attr_accessible :image, :name, :name_english, :pdf_flashcards, :pdf_worksheet, :description, :video_url, :theme_id, :subtheme_identifier
  belongs_to :theme
  has_many :words
  has_one :language, :through => :theme
  #has_and_belongs_to_many :words
end

app/models/subthemes_words.rb
class SubthemesWords < ActiveRecord::Base
  attr_accessible :image, :mp3, :pdf, :subtheme_id, :word_english, :word_foreign, :word_foreign_image, :word_id
  belongs_to :subtheme
  belongs_to :word
end

app/models/theme.rb
class Theme < ActiveRecord::Base
  attr_accessible :name, :name_english, :image, :pdf, :language_id, :description, :theme_identifier
  belongs_to :language
  has_many :subthemes
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/word.rb
class Word < ActiveRecord::Base
  attr_accessible :image, :mp3, :name, :name_english, :name_image, :pdf, :subtheme_id, :word_identifier

  belongs_to :subtheme

  has_one :theme, :through => :subtheme
  has_one :language, :through => :theme
  # validates :name, :uniqueness => true
  #belongs_to :language, :through => :theme

  #has_and_belongs_to_many :subthemes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/language_tables_controller.rb
class LanguageTablesController < ApplicationController
end

app/controllers/languages_controller.rb
class LanguagesController < ApplicationController
  def show
  	@language = Language.find(params[:id])
  end
end

app/controllers/subthemes_controller.rb
class SubthemesController < ApplicationController
	before_filter :authenticate_user!
	def show
		@subtheme = Subtheme.find(params[:id])
  	end
end

app/controllers/themes_controller.rb
class ThemesController < ApplicationController
	before_filter :authenticate_user!
	def show
		@theme = Theme.find(params[:id])
	end	
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
	before_filter :authenticate_user!
	def show
		if params[:word_id]
			@language = Language.find(params[:language_id])
			@theme = Theme.find(params[:language_id])
			@subtheme = Subtheme.find(params[:subtheme_id])
  			@word = Word.find(params[:word_id])
  		else
  			@word = Word.find(params[:id])
  		end

	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/helpers/subtheme_helper.rb
module SubthemeHelper
end

app/helpers/subthemes_helper.rb
module SubthemesHelper
end

app/helpers/theme_helper.rb
module ThemeHelper
end

app/helpers/themes_helper.rb
module ThemesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/helpers/words_subthemes_helper.rb
module WordsSubthemesHelper
end

app/views/languages/show.html.erb
    <div class="container">

      <!-- Main hero unit for a primary marketing message or call to action -->
      <div class="hero-unit-smaller">
        <% if params[:controller] == 'languages' %>
        	<% language = Language.find(params[:id]) %>
        	<h1><%= language.name_english %></h1>
        <% end %>
        <p>Select a theme</p>
        <p>
        	<% @language.themes.each do |t| %>
          	<div style="display:inline-block;width:200px;">
            	<div style="width:200px;text-align:center;margin-left:10px;">
            	<%= link_to theme_path(t) do %>
                <%= t.name_english %>
                <span style="font-size:11px"><%= t.name %></span></div>
                <%= image_tag t.image, width: '200' %>
              <% end %>
          	</div>
        	<% end %>
        </p>
      </div>

    </div>

app/views/words/show.html.erb
    <div class="container">

      <!-- Main hero unit for a primary marketing message or call to action -->
      <div class="hero-unit-smaller">
        <h1><%= @word.name %></h1>
        <p><%= @word.name_english %></p>

        <p>View the word
        	<%= link_to 'pdf file', @word.pdf %> or play the audio file
      	</p>
        <p>
        	<audio controls loop style="width:600px;margin-left:10px;">
        	<source src="<%= @word.mp3 %>" type="audio/mpeg">
        	Your browser does not support the audio element.
        	</audio>
        	<%#= link_to 'View the pdf file', @word.pdf %>
        </p>

        <p>
        <%= image_tag @word.image %></p>
        <%#= image_tag @word.image, width: '600', height: '400' %></p>
        </p>
      </div>

      <!-- 
      View the same word in other languages
      <ul>
      	<% SubthemesWords.where('word_id = ?', @word.id).each do |s| %>
      		<li>
      			<%= Subtheme.find(s.subtheme_id).theme.language.name_english %>
      		</li>
      	<% end %>
      </ul>
      -->
    </div>