config/routes.rb
SfsLanguages::Application.routes.draw do

  devise_for :users

  resources :language_tables

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :words_subthemes

  resources :words

  get "subtheme/show"

  resources :subthemes

  get "theme/show"

  resources :themes

  get "welcome/index"

  get "languages/show"

  match ':language_id/:theme_id/:subtheme_id/:word_id' => 'words#show'

  resources :languages do
    resources :themes do
      resources :subthemes do
        resources :words
      end
    end
  end

  root :to => 'welcome#index'
  ActiveAdmin.routes(self)

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/language.rb
class Language < ActiveRecord::Base
  attr_accessible :description, :name, :name_english, :language_identifier
  has_many :themes
end

app/models/subtheme.rb
class Subtheme < ActiveRecord::Base
  attr_accessible :image, :name, :name_english, :pdf_flashcards, :pdf_worksheet, :description, :video_url, :theme_id, :subtheme_identifier
  belongs_to :theme
  has_many :words
  has_one :language, :through => :theme
  #has_and_belongs_to_many :words
end

app/models/subthemes_words.rb
class SubthemesWords < ActiveRecord::Base
  attr_accessible :image, :mp3, :pdf, :subtheme_id, :word_english, :word_foreign, :word_foreign_image, :word_id
  belongs_to :subtheme
  belongs_to :word
end

app/models/theme.rb
class Theme < ActiveRecord::Base
  attr_accessible :name, :name_english, :image, :pdf, :language_id, :description, :theme_identifier
  belongs_to :language
  has_many :subthemes
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/word.rb
class Word < ActiveRecord::Base
  attr_accessible :image, :mp3, :name, :name_english, :name_image, :pdf, :subtheme_id, :word_identifier

  belongs_to :subtheme

  has_one :theme, :through => :subtheme
  has_one :language, :through => :theme
  # validates :name, :uniqueness => true
  #belongs_to :language, :through => :theme

  #has_and_belongs_to_many :subthemes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/language_tables_controller.rb
class LanguageTablesController < ApplicationController
end

app/controllers/languages_controller.rb
class LanguagesController < ApplicationController
  def show
  	@language = Language.find(params[:id])
  end
end

app/controllers/subthemes_controller.rb
class SubthemesController < ApplicationController
	before_filter :authenticate_user!
	def show
		@subtheme = Subtheme.find(params[:id])
  	end
end

app/controllers/themes_controller.rb
class ThemesController < ApplicationController
	before_filter :authenticate_user!
	def show
		@theme = Theme.find(params[:id])
	end	
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
	before_filter :authenticate_user!
	def show
		if params[:word_id]
			@language = Language.find(params[:language_id])
			@theme = Theme.find(params[:language_id])
			@subtheme = Subtheme.find(params[:subtheme_id])
  			@word = Word.find(params[:word_id])
  		else
  			@word = Word.find(params[:id])
  		end

	end
end

app/controllers/words_subthemes_controller.rb
class WordsSubthemesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/helpers/subtheme_helper.rb
module SubthemeHelper
end

app/helpers/subthemes_helper.rb
module SubthemesHelper
end

app/helpers/theme_helper.rb
module ThemeHelper
end

app/helpers/themes_helper.rb
module ThemesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/helpers/words_subthemes_helper.rb
module WordsSubthemesHelper
end

app/views/subthemes/show.html.erb
    <div class="container">

      <!-- Main hero unit for a primary marketing message or call to action -->
      <div class="hero-unit-smaller">
      	<% subtheme = Subtheme.find(params[:id]) %>
        <h1><%= subtheme.name %></h1>
        <p><%= subtheme.name_english %></p>

        <p>View the 
        	<%= link_to 'flashcards', @subtheme.pdf_flashcards %>, 
        	<%= link_to 'worksheets', @subtheme.pdf_worksheet %>, or select a word</p>
        <p>
        	<ul>
          	<% @subtheme.words.each do |w| %>
            	<div style="display:inline-block;width:110px;">
              	<div style="width:100px;text-align:center;margin-left:10px;">
                	<%= link_to word_path(w) do %>
                    <%= w.name_english %>
                    <br/><span style="font-size:11px"><%= w.name %></span></div>
                    <%= image_tag w.image, width: '100' %>
                  <% end %>
            	</div>
          	<% end %>
        	</ul>
        </p>
      </div>

    </div>

app/views/themes/show.html.erb
    <div class="container">

      <!-- Main hero unit for a primary marketing message or call to action -->
      <div class="hero-unit-smaller">
      	<% theme = Theme.find(params[:id]) %>
        <h1><%= theme.name %></h1>
        <p><%= theme.name_english %></p>
        <p>View the 
        	<%= link_to 'coloring book', @theme.pdf %> or select a sub-theme</p>
        <p>
        	<ul>
        		<% Subtheme.where('theme_id = ?', "#{@theme.id}").each do |s| %>
        			<li><%= link_to s.name_english, subtheme_path(s) %> <span style="font-size:11px"><%= s.name %></span></li>
        		<% end %>
        	</ul>
        </p>
      	<%= image_tag @theme.image, width: '200', height: '300' %>
      	<%#= image_tag @theme.image, width: '400', height: '600' %>

      </div>

    </div>